---
title: "Untitled"
author: "Daniel Chen"
date: "01/24/2015"
output:
  html_document:
    toc: yes
runtime: shiny
---

```{r, echo=FALSE, warning=FALSE}
library(ggplot2)
library(scales)
library(foreach)
library(doParallel)
library(knitr)

opts_chunk$set(echo=FALSE#,
               # fig.path='Figs-batch_analysis_stacked/',
               # dpi=120,
               # fig.width=8,
               # fig.height=8
               )

source(file = '../helper.R')
source(file = '../helper_config.R')
source(file = '../../analysis_config.R')

cl <- makeCluster(config_num_cores)
registerDoParallel(cl)
```

## Batch sweep experiment
### Average SSE of agents who have been updated
```{r, echo=FALSE, cache=TRUE}
strt <- Sys.time()
load('../../../results/simulations/02-lens_batch_2014-12-23_03:41:22_sm_partial_df_grouped_runs_list.RData')
print_difftime_prompt('load grouped data', diff_time = Sys.time() - strt)
```

```{r}
starts <- seq(from = 1, to = ncol(reshape_files), by = config_num_parameter_sets_no_a)
strt <- Sys.time()
plots_facet <- foreach(i = 1:length(starts), .packages=c('ggplot2'),
                       .export=c('config_num_parameter_sets_no_a')) %dopar% {
    start <- starts[i]
    end <- start + config_num_parameter_sets_no_a - 1
    df_all_n <- plyr::ldply(list_stacked_df_grouped[start:end], data.frame)
    g <- ggplot(df_all_n[df_all_n$ever_updated == 1, ], 
                aes(time, color = as.factor(run_number))) + 
        theme(legend.position="none") +
        geom_line(aes(y = avg_sse)) + scale_y_continuous(limits=c(0, 20)) +
        theme(axis.text.x=element_text(angle = -90, hjust = 0)) +
        facet_grid(delta_value~epsilon_value, labeller = label_both)
    g
}
print_difftime_prompt('generate faceted plots', diff_time = Sys.time() - strt)
```

```{r, echo=FALSE}
stopCluster(cl)
registerDoSEQ()
```

```{r, echo=FALSE}
inputPanel(
  selectInput("select", label = h3("Select Plot"), 
    choices = list("N = 10" = 1, "N = 100" = 2, "N = 1,000" = 3), 
    selected = 1)
)

renderPlot({
  plots_facet[as.numeric(input$select)]
})
```

## Processing unit activation values (only those updated)
```{r, echo=FALSE, cache=TRUE}
strt <- Sys.time()
load('../../../results/simulations/02-lens_batch_2014-12-23_03:41:22_sm_partial_df_stacked_runs_updated_melt_list.RData')
print_difftime_prompt('load stacked updated only long data', diff_time = Sys.time() - strt)
```

```{r, echo=FALSE}
test_df_melt <- list_only_updated_melt[[1]]
```

```{r, echo=FALSE}
###############################################################################
# Plot all processing unit activation values over all time
# Save plot to variable g
# g will be used to subset the x-axis
###############################################################################

inputPanel(
    selectInput("select_subplot_delta", label = "Select Plot Delta", 
                choices = list("0%" = 1, "25%" = 2, "50%" = 3, "75%" = 4, "100%" = 5),
                selected = 1),
    selectInput("select_subplot_epsilon", label = "Select Plot Epsilon", 
                choices = list("0%" = 1, "10%" = 2, "20%" = 3, "30%" = 4, "40%" = 5, "50%" = 6), 
                selected = 1),
    br(),
    sliderInput("activation_adjust", label = "Activation Value Adjust",
                min = 0, max = 1, value = c(0, 1), step = .05),
    
    sliderInput("time_adjust", label = "Time Range Adjust",
                min = 0, max = 10000, value = c(100, 1000), step = 50),
    actionButton("goButton", "Zoom!"),
    p("Click the button to subset the plot.")
)

renderPlot({
    strt <- Sys.time()
    g1 <- ggplot(data = test_df_melt) +
        geom_line(aes(x = time, y = value, color=variable)) + facet_grid(run_number~variable) +
        theme(legend.position="none", axis.text.x = element_text(angle=90, vjust=0.5))
    print_difftime_prompt('create ggplot object', diff_time = Sys.time() - strt)
    
    strt <- Sys.time()
    print(g1)
    print_difftime_prompt('show ggplot object', diff_time = Sys.time() - strt)
    
    hr()
    
    input$goButton
    strt <- Sys.time()
    print(g1 + scale_y_continuous(limits=isolate(input$activation_adjust),
                                  breaks=pretty_breaks()) +
              scale_x_continuous(limits=isolate(input$time_adjust),
                                 breaks=pretty_breaks()))
    print_difftime_prompt('create ggplot object subset y-axis', diff_time = Sys.time() - strt)
})

```

```{r, echo=FALSE}
###############################################################################
# Use sliders to subset the plot by time (x-axis)
###############################################################################
# inputPanel(
#     sliderInput("activation_adjust", label = "Activation Value Adjust",
#                 min = 0, max = 1, value = c(0, 1), step = .05),
#     
#     sliderInput("time_adjust", label = "Time Range Adjust",
#                 min = 0, max = 10000, value = c(100, 1000), step = 50),
#     actionButton("goButton", "Zoom!"),
#     p("Click the button to subset the plot.")
# )
# 
# renderPlot({
#     input$goButton
#     strt <- Sys.time()
#     print(g1 + scale_y_continuous(limits=isolate(input$activation_adjust),
#                                  breaks=pretty_breaks()) +
#               scale_x_continuous(limits=isolate(input$time_adjust),
#                                  breaks=pretty_breaks()))
# })
# print_difftime_prompt('create ggplot object subset y-axis', diff_time = Sys.time() - strt)
```



