---
title: "calibration_analysis"
output:
  html_document:
    fig_height: 8
    fig_width: 10.5
---
```{r}
library(ggplot2)
delta_calibration_tables <- read.csv("~/Desktop/delta_calibration_tables.csv",
                                     stringsAsFactors=FALSE)

data <- delta_calibration_tables
```

# plot number of epochs
```{r}
d <- data[data$delta == 0.2, ]
ggplot(data = d, aes(x=epochs)) + geom_histogram(binwidth=1000) +
  scale_x_continuous(breaks = round(seq(min(d$epochs),
                                        max(d$epochs),
                                        by = 1000),
                                    1000)) +
  theme(axis.text.x=element_text(angle = -90, hjust = 0))

d <- data[data$delta == 0.5, ]
ggplot(data = d, aes(x=epochs)) + geom_histogram(binwidth=1000) +
  scale_x_continuous(breaks = round(seq(min(d$epochs),
                                        max(d$epochs),
                                        by = 1000),
                                    1000)) +
  theme(axis.text.x=element_text(angle = -90, hjust = 0))
```


# plot errors
```{r}
ggplot(data = data, aes(x=error)) + geom_histogram() + facet_grid(~ delta)
```







```

