---
title: "mann-r-analysis"
author: "Daniel Chen"
output:
  html_document:
    fig_height: 11
    fig_width: 11
    number_sections: yes
    toc: yes
---
```{r, echo=FALSE, message=FALSE}
library(lsa)
library(stringr)
library(ggplot2)
library(reshape2)
library(ggthemes)
library(knitr)
library(foreach)
library(doMC)
library(grid)
library(dplyr)
opts_chunk$set(echo=FALSE,
               fig.path='Figs-batch_analysis/',
               dpi=300,
               fig.width=11,
               fig.height=11)
rm(list=ls())
```

```{r}
# parameters to run script
# get list of .pout files
batch_folder <- '02-lens_batch_2014-12-23_03:41:22_sm_partial'
batch_folder <- 'bkup_02-lens_batch_2014-12-23_03:41:22'

num_processing_units <- 20
activation_value_columns <- c(6:25)
prototype_value_columns <- c(66:85)
```


```{r, echo=FALSE}
multiplot <- function(list_of_plots, plotlist=NULL, file, cols=1, layout=NULL) {
  # Make a list from the ... arguments and plotlist
  # plots <- c(list(...), plotlist)
  plots <- c(list_of_plots, plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


```{r, echo=FALSE}
get_batch_pout_files <- function(batch_folder){
    batch_experiments <- list.files(batch_folder)
    pout_files <- c()
    for(batch_experiment in batch_experiments){
        pout_path <- paste(batch_folder, batch_experiment, 'output', sep = '/')
        pout_path_file <- paste(pout_path, 'network_of_agents.pout', sep = '/')
        pout_files <- c(pout_files, pout_path_file)
    }
    print(pout_files)
    return(pout_files)
}
```

```{r}
get_data <- function(pout_file){
    df <- read.csv(pout_file, header = FALSE, nrow = 10030)
    names(df)[1:5] <- c('time', 'agent', 'numUpdate', 'isUpdated', 'inflId')
    prototype <- c((ncol(df) - 19) : ncol(df))
    activationValues <- c(6:25)
    return(df)
}
```


```{r}
calculate_sse <- function(vector){
  activationValues <- vector[activation_value_columns]
  prototype <- vector[prototype_value_columns]
  difference <- as.numeric(activationValues) - as.numeric(prototype)
  se <- difference ** 2
  sse <- sum(se)
  return(sse)
}
```

```{r}
calculate_cosine_sim <- function(vector){
  activationValues <- vector[activation_value_columns]
  prototype <- vector[prototype_value_columns]
  
  v1 <- as.vector(as.matrix(as.numeric(activationValues) + 1))
  v2 <- as.vector(as.matrix(as.numeric(prototype) + 1))

  cosine <- lsa::cosine(v1, v2)
  return(cosine)
}
```

```{r}
create_plots <- function(dataframe, foldername){
    g <- ggplot(dataframe, aes(time)) + ggtitle(foldername) + theme(plot.title = element_text(size = rel(0.9)))
    
    g.sse <- g + geom_line(aes(y = avgSse)) 
    g.sse
    
    g.cos <- g + geom_line(aes(y = avgCos))
    g.cos
    
    g.cumAgentUpdate <-g + geom_line(aes(y = cumAgentUpdate))
    g.cumAgentUpdate
    
    g.cos80 <- g + geom_line(aes(y = propCos80))
    g.cos80

    g.cos85 <- g + geom_line(aes(y = propCos85))
    g.cos85
    
    g.cos90 <- g + geom_line(aes(y = propCos90))
    g.cos90
    
    g.cos95 <- g + geom_line(aes(y = propCos95))
    g.cos95
    
    g.cos97 <- g + geom_line(aes(y = propCos97))
    g.cos97
    
    g.cos99 <- g + geom_line(aes(y = propCos99))
    g.cos99
    
    g.cos999 <- g + geom_line(aes(y = propCos999))
    g.cos999

    # g.cos80.updated <- c()
    # g.cos90.updated <- c()
    
    return(list(g.sse, g.cos, g.cumAgentUpdate, g.cos80, g.cos85, g.cos90,
                g.cos95, g.cos97, g.cos99, g.cos999))
}
```


```{r}
strt <- Sys.time()
pout_files <- get_batch_pout_files(batch_folder)
pout_file <- pout_files[1]
# for each pout file, clean and plot it

# registerDoMC(4)
# par_list <- foreach(i=1:length(pout_files)) %dopar% {
for(i in 1:length(pout_files)){
# get data
    pout_file <- pout_files[i]
    pout_file
    df <- get_data(pout_file)
    
    # calculate sum square error values
    df2 <- df
    df2$sse <- apply(df2, MARGIN = 1, calculate_sse)

    # calculate cosine values
    df2$cos <- apply(df2, 1, calculate_cosine_sim)

    # recode cosine values
    df2$cos80 <- ifelse(df2$cos >= .80, yes = 1, no = 0)
    df2$cos85 <- ifelse(df2$cos >= .85, yes = 1, no = 0)
    df2$cos90 <- ifelse(df2$cos >= .90, yes = 1, no = 0)
    df2$cos95 <- ifelse(df2$cos >= .95, yes = 1, no = 0)
    df2$cos97 <- ifelse(df2$cos >= .97, yes = 1, no = 0)
    df2$cos99 <- ifelse(df2$cos >= .99, yes = 1, no = 0)
    df2$cos999 <- ifelse(df2$cos >= .999, yes = 1, no = 0)
    
    # assign update status
    df2$ifEverUpdated <- ifelse(df2$numUpdate >= 1, 1, 0)
    
    # assign time to 90% saturation
    
    # calculate cosine similiary proportions
        df3 <- df2 %>%
            group_by(time) %>%
            summarize(avgSse = mean(sse),
                      avgCos = mean(cos),
                      cumAgentUpdate = sum(ifEverUpdated),
                      n = n(),
                      propCos80 = sum(cos80) / n(),
                      propCos85 = sum(cos85) / n(),
                      propCos90 = sum(cos90) / n(),
                      propCos95 = sum(cos95) / n(),
                      propCos97 = sum(cos97) / n(),
                      propCos99 = sum(cos99) / n(),
                      propCos999 = sum(cos999) / n()
                      ) %>%
            mutate(freq = cumAgentUpdate / n)
    
    # calculate cosine similiary proportions given update status
        df4 <- df2 %>%
            group_by(time, ifEverUpdated) %>%
            summarise(avgSse = mean(sse),
                      avgCos = mean(cos),
                      cumAgentUpdate = sum(ifEverUpdated),
                      n = n(),
                      propCos80 = sum(cos80) / n(),
                      propCos85 = sum(cos85) / n(),
                      propCos90 = sum(cos90) / n(),
                      propCos95 = sum(cos95) / n(),
                      propCos97 = sum(cos97) / n(),
                      propCos99 = sum(cos99) / n(),
                      propCos999 = sum(cos999) / n()
                      )
    
#     ever_updated_status <- group_by(df2, time, ifEverUpdated)
# 
#     per_ever_updated_status <- ever_updated_status %>%
#         summarise(avgSse = mean(sse),
#                   avgCos = mean(cos),
#                   cumAgentUpdate = sum(ifEverUpdated),
#                   n = n(),
#                   numCos80 = sum(cos80),
#                   numCos85 = sum(cos85),
#                   numCos90 = sum(cos90),
#                   numCos95 = sum(cos95),
#                   numCos97 = sum(cos97),
#                   numCos99 = sum(cos99),
#                   numCos999 = sum(cos999),
# 
#                   propCos80 = sum(cos80) / n(),
#                   propCos85 = sum(cos85) / n(),
#                   propCos90 = sum(cos90) / n(),
#                   propCos95 = sum(cos95) / n(),
#                   propCos97 = sum(cos97) / n(),
#                   propCos99 = sum(cos99) / n(),
#                   propCos999 = sum(cos999) / n()
#                   )
#     
#     per_time <- mutate(per_ever_updated_status,
#                        avgSse = sum(avgSse * n) / sum(n),
#                        avgCos = sum(avgCos * n) / sum(n),
#                        cumAgentUpdate = sum(cumAgentUpdate),
#                        n = sum(n),
#                        numCos80 = sum(numCos80),
#                        numCos85 = sum(numCos85),
#                        numCos90 = sum(numCos90),
#                        numCos95 = sum(numCos95),
#                        numCos97 = sum(numCos97),
#                        numCos99 = sum(numCos99),
#                        numCos999 = sum(numCos999),
# 
#                        propCos80 = numCos80 / n,
#                        propCos85 = numCos85 / n,
#                        propCos90 = numCos90 / n,
#                        propCos95 = numCos95 / n,
#                        propCos97 = numCos97 / n,
#                        propCos99 = numCos99 / n,
#                        propCos999 = numCos999 / n
#                        ) %>%
#         filter(ifEverUpdated == 0) %>%
#         select(-(ifEverUpdated))

    # create each plot
    foldername <- str_split(string = pout_file, "/")[[1]][2]

    plots <- create_plots(df3, paste(foldername, 'all', sep = '_'))
    plots_2 <- create_plots(df4[df4$ifEverUpdated == 0, ], paste(foldername, 'updated_only', sep = '_'))

    # multiplot
    print(pout_file)
    multiplot(c(plots, plots_2), cols = 4)
break
}
print("total time:")
print(Sys.time() - strt)

```

```{r}
# registerDoMC(4)
# par_list <- foreach(i=1:10) %dopar% {
# 
#  print(i)
#  empty <- c()
#  empty <- c(empty, i)
# }
# par_list
```

